export const FETCH_TVSHOWS = 'FETCH_TVSHOWS';
export const FETCH_TVSHOWS_FAILURE = 'FETCH_TVSHOWS_FAILURE';
export const FETCH_TVSHOWS_FULLFILLED = 'FETCH_TVSHOWS_FULLFILLED';
export const FETCH_TVSHOWS_LOADING = 'FETCH_TVSHOWS_LOADING';